project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality-control/', include('quality_control.urls')),
]

quality_control/urls.py
from django.urls import path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    # Index
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),

    # Bug Reports
    # FBV
    # path('bugs/', views.bug_list, name='bugs'),
    # path('bugs/new/', views.create_bug_report, name='create_bug_report'),
    # path('bugs/<int:bug_id>', views.bug_report_detail, name='bug_detail'),
    # path('bugs/<int:bug_id>/update/', views.update_bug_report, name='update_bug_report'),
    # path('bugs/<int:bug_id>/delete/', views.delete_bug_report, name='delete_bug_report'),

    # CBV
    path('bugs/', views.BugReportsListView.as_view(), name='bugs'),
    path('bugs/new/', views.BugReportCreateView.as_view(), name='create_bug_report'),
    path('bugs/<int:bug_id>', views.BugDetailView.as_view(), name='bug_detail'),
    path('bugs/<int:bug_id>/update/', views.BugReportUpdateView.as_view(), name='update_bug_report'),
    path('bugs/<int:bug_id>/delete/', views.BugReportDeleteView.as_view(), name='delete_bug_report'),

    # Feature Requests
    # FBV
    # path('features/', views.feature_list, name='features'),
    # path('features/new/', views.create_feature_request, name='create_feature_request'),
    # path('features/<int:feature_id>', views.feature_request_detail, name='feature_request_detail'),
    # path('features/<int:feature_id>/update/', views.update_feature_request, name='update_feature_request'),
    # path('features/<int:feature_id>/delete/', views.delete_feature_request, name='delete_feature_request'),

    # CBV
    path('features/', views.FeatureRequestsListView.as_view(), name='features'),
    path('features/new/', views.FeatureRequestCreateView.as_view(), name='create_feature_request'),
    path('features/<int:feature_id>', views.FeatureDetailView.as_view(), name='feature_request_detail'),
    path('features/<int:feature_id>/update/', views.FeatureRequestUpdateView.as_view(), name='update_feature_request'),
    path('features/<int:feature_id>/delete/', views.FeatureRequestDeleteView.as_view(), name='delete_feature_request'),
]

tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    # FBV
    # path('', views.index, name='index'),
    # path('projects/', views.projects_list, name='projects_list'),
    # path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    # path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    # path('project/new/', views.create_project, name='create_project'),
    # path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    # path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    # path('project/<int:project_id>/tasks/<int:task_id>/update/', views.update_task, name='update_task'),
    # path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),

    # CBV
    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('project/new/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),

    path('feedback/', views.feedback_view, name='feedback'),

]

quality_control/models.py
from django.db import models

from tasks.models import Project, Task


class BugReport(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.SET_NULL, null=True, blank=True)
    STATUS_CHOICES = [('N', 'New'), ('I', 'In Progress'), ('C', 'Closed')]
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='N')
    PRIORITY_CHOICES = [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
    priority = models.IntegerField(choices=PRIORITY_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + ' [' + self.get_status_display() + ']'


class FeatureRequest(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.SET_NULL, null=True, blank=True)
    STATUS_CHOICES = [('C', 'Consideration'), ('A', 'Accepted'), ('R', 'Rejected')]
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    PRIORITY_CHOICES = [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
    priority = models.IntegerField(choices=PRIORITY_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + ' [' + self.get_status_display() + ']'

quality_control/forms.py
from django import forms
from .models import BugReport, FeatureRequest


class BugReportForm(forms.ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'project', 'task', 'status', 'priority']


class FeatureRequestForm(forms.ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'project', 'task', 'status', 'priority']


class FeedbackForm(forms.Form):
    name = forms.CharField(label='Ваше имя', max_length=100)
    email = forms.EmailField(label='Электронная почта')
    message = forms.CharField(widget=forms.Textarea, label='Сообщение')

quality_control/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import View, DetailView, UpdateView, DeleteView, ListView, CreateView

from quality_control.forms import BugReportForm, FeatureRequestForm
from quality_control.models import BugReport, FeatureRequest


def index(request):
    return render(request, 'quality_control/index.html')


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')


def bug_list(request):
    return render(request, 'quality_control/bug_list.html', {'bugreport_list': BugReport.objects.all()})


class BugReportsListView(ListView):
    model = BugReport
    template_name = 'quality_control/bug_list.html'


class BugDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        bug = self.object

        return render(request, 'quality_control/bug_detail.html', {'bug': bug})


def feature_list(request):
    return render(request, 'quality_control/feature_list.html',
                  {'featurerequest_list': FeatureRequest.objects.all()})


class FeatureRequestsListView(ListView):
    model = FeatureRequest
    template_name = 'quality_control/feature_list.html'


def bug_report_detail(request, bug_id):
    return render(request, 'quality_control/bug_detail.html', {'bug': get_object_or_404(BugReport, pk=bug_id)})


def feature_request_detail(request, feature_id):
    feature_req = get_object_or_404(FeatureRequest, pk=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'feature': feature_req})


class FeatureDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        feature = self.object

        return render(request, 'quality_control/feature_detail.html', {'feature': feature})


def create_bug_report(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bugs')
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_report_form.html', {'form': form})


class BugReportCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_form.html'
    success_url = reverse_lazy('quality_control:bugs')


def create_feature_request(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:features')
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_request_form.html', {'form': form})


class FeatureRequestCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_form.html'
    success_url = reverse_lazy('quality_control:features')


def update_bug_report(request, bug_id):
    project = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bugs')
    else:
        form = BugReportForm(instance=project)
    return render(request, 'quality_control/bug_report_update.html', {'form': form, 'project': project})


def update_feature_request(request, feature_id):
    project = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('quality_control:features')
    else:
        form = FeatureRequestForm(instance=project)
    return render(request, 'quality_control/feature_request_update.html', {'form': form, 'project': project})


class BugReportUpdateView(UpdateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_update.html'
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bugs')


class FeatureRequestUpdateView(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_update.html'
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:features')


def delete_bug_report(request, bug_id):
    project = get_object_or_404(BugReport, pk=bug_id)
    project.delete()
    return redirect('quality_control:bugs')


def delete_feature_request(request, feature_id):
    task = get_object_or_404(FeatureRequest, pk=feature_id)
    task.delete()
    return redirect('quality_control:features')


class BugReportDeleteView(DeleteView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bugs')
    template_name = 'quality_control/bug_report_confirm_delete.html'


class FeatureRequestDeleteView(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:features')
    template_name = 'quality_control/feature_request_confirm_delete.html'

quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <p><a href="{% url 'quality_control:update_bug_report' bug.id %}">Изменить отчет об ошибке</a></p>
    <p><a href="{% url 'quality_control:delete_bug_report' bug.id %}">Удалить отчет об ошибке</a></p>
    <h1>Title: {{ bug.title }}</h1>
    <p>Description: {{ bug.description }}</p>
    <p><a href="{% url 'tasks:project_detail' bug.project.id %}">Project: {{ bug.project }}</a></p>
    <p><a href="{% url 'tasks:task_detail' bug.project.id bug.task.id %}">Task: {{ bug.task }}</a></p>
    <p>Status: {{ bug.get_status_display }}</p>
    <p>Priority: {{ bug.priority }}</p>
    <p>Created at: {{ bug.created_at }}</p>
    <p>Updated at: {{ bug.updated_at }}</p>
{% endblock %}

quality_control/templates/quality_control/bug_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список отчетов об ошибках</h1>
    <p><a href="{% url 'quality_control:create_bug_report' %}">Создать новый отчет</a></p>

    <ul>
        {% for bug_report in bugreport_list %}
            <li><a href="{% url 'quality_control:bug_detail' bug_report.id %}">{{ bug_report }}</a></li>
        {% empty %}
            <li>Пока нет отчетов об ошибках</li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/bug_report_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление отчета об ошибке</h1>
    <p>Вы уверены, что хотите удалить отчет об ошибке "{{ bugreport.title }}"?</p>

    <form action="{% url 'quality_control:delete_bug_report' bugreport.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bug_detail' bugreport.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Создать новый отчет об ошибке</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_report_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение отчета об ошибке: {{ bug.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <p><a href="{% url 'quality_control:update_feature_request' feature.id %}">Изменить запрос</a></p>
    <p><a href="{% url 'quality_control:delete_feature_request' feature.id %}">Удалить запрос</a></p>
    <h1>Title: {{ feature.title }}</h1>
    <p>Description: {{ feature.description }}</p>
    <p><a href="{% url 'tasks:project_detail' feature.project.id %}">Project: {{ feature.project }}</a></p>
    <p><a href="{% url 'tasks:task_detail' feature.project.id feature.task.id %}">Task: {{ feature.task }}</a></p>
    <p>Status: {{ feature.get_status_display }}</p>
    <p>Priority: {{ feature.priority }}</p>
    <p>Created at: {{ feature.created_at }}</p>
    <p>Updated at: {{ feature.updated_at }}</p>
{% endblock %}

quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список запросов на улучшение</h1>
    <p><a href="{% url 'quality_control:create_feature_request' %}">Создать новый запрос</a></p>

    <ul>
        {% for feature in featurerequest_list %}
            <li><a href="{% url 'quality_control:feature_request_detail' feature.id %}">{{ feature }}</a></li>
        {% empty %}
            <li>Пока нет запросов на улучшение</li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/feature_request_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса на улучшение</h1>
    <p>Вы уверены, что хотите удалить запрос на улучшение? "{{ featurerequest.title }}"?</p>

    <form action="{% url 'quality_control:delete_feature_request' featurerequest.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_request_detail' featurerequest.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Создать новый запрос на улучшение</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_request_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение запроса на улучшение: {{ feature_request.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Система контроля качества</h1>
    <a href="{% url 'quality_control:bugs' %}">Список всех багов</a>
    <a href="{% url 'quality_control:features' %}">Запросы на улучшение</a>
{% endblock %}